src/Walltage.Web/Controllers/CommonController.cs
using log4net;
using System.Web.Mvc;
using Walltage.Service.Wrappers;
using Walltage.Web.Models.Common;

namespace Walltage.Web.Controllers
{
    public class CommonController : Controller
    {        
        private readonly ISessionWrapper _sessionWrapper;
        private readonly ICookieWrapper _cookieWrapper;
        private readonly ILog _logger;

        public CommonController(ILog logger,
            ISessionWrapper sessionWrapper,
            ICookieWrapper cookieWrapper)
        {
            _logger = logger;
            _cookieWrapper = cookieWrapper;
            _sessionWrapper = sessionWrapper;
        }

        [ChildActionOnly]
        public ActionResult HeaderLinks()
        {
            var model = new HeaderLinksModel();
            model.IsAuthenticated = false;
            if (!string.IsNullOrEmpty(_sessionWrapper.UserName))
            {
                model.IsAuthenticated = true;
                model.Username = _sessionWrapper.UserName;
            }
            return PartialView(model);
        }
    }
}

src/Walltage.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- META Tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Walltage</title>
    <meta name="description" content="@ViewBag.Description" />
    <meta name="keyword" content="@ViewBag.Keyword" />
    <meta name="author" content="Abdurrahman ISIK" />
    <!-- Facebook Metadata /-->
    <meta property="fb:page_id" content="" />
    <meta property="og:image" content="" />
    <meta property="og:description" content="" />
    <meta property="og:title" content="" />

    <!-- CSS Files -->
    <link href="~/assets/css/font-awesome.min.css" rel="stylesheet" />
    @Styles.Render("~/bundles/css")
    <!-- Font & Favicon -->
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic" rel='stylesheet' type='text/css' />
    <link href='http://fonts.googleapis.com/css?family=Dosis:200,400,500,600,800&subset=latin,latin-ext' rel='stylesheet' type='text/css' />
    <link rel="icon" href="~/assets/images/favicon.ico" type="image/x-icon" />
    <!-- Google Analytics Code -->
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="/" class="navbar-brand" title="Walltage">Walltage</a>
                </div>

                <div class="collapse navbar-collapse" id="main-navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="~/home/mostviewed"><i class="fa fa-eye"></i> Most Viewed</a></li>
                        <li><a href="~/home/random"><i class="fa fa-random"></i> Random</a></li>
                        <li><a href="~/home/upload"><i class="fa fa-comments"></i> Upload</a></li>
                    </ul>
                    @Html.Action("HeaderLinks", "Common")
                </div>
            </div>
        </nav>

        <!-- Content -->
        @RenderBody()

        <div class="footer-ghost"></div>
    </div>
    <footer>
        <ul>
            <li><a href="https://twitter.com/walltage" class="fa fa-twitter"><span class="label">Twitter</span></a></li>
            <li><a href="https://www.facebook.com/pages/Walltage/702957579746423?ref=hl" class="fa fa-facebook"><span class="label">Facebook</span></a></li>
            <li><a href="https://github.com/xJason21/Walltage" class="fa fa-github"><span class="label">GitHub</span></a></li>
            <li><a href="mailto:walltageweb@gmail.com" title="Say Hello !" class="fa fa-envelope"><span class="label">Email</span></a></li>
        </ul>
        <ul class="copyright">
            <li>@DateTime.Now.AddYears(-1).Year &copy; Walltage. All rights reserved.</li>
            <li>Made with <i class="fa fa-heart"></i> in Istanbul, Turkey </li>
        </ul>
    </footer>

    <!-- Script Files -->
    @Scripts.Render("~/bundles/jquery")
    <script src="~/Assets/js/knockout-3.4.1.js"></script>
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/js")
    @RenderSection("scripts", required: false)
    <!-- Google Analytics -->
</body>
</html>